name = "gourmoire-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# D1 Database binding (already exists)
[[d1_databases]]
binding = "DB"
database_name = "gourmoire-db"
database_id = "gourmoire-database-id"

# KV Namespaces for JWT authentication
[[kv_namespaces]]
binding = "USERS_KV"
id = "users_kv_namespace"
preview_id = "users_kv_namespace_preview"

[[kv_namespaces]]
binding = "RECIPES_KV"
id = "recipes_kv_namespace"
preview_id = "recipes_kv_namespace_preview"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth_kv_namespace"
preview_id = "auth_kv_namespace_preview"

# Environment variables for JWT secrets
# These should be set in Cloudflare dashboard or via wrangler secret:
# wrangler secret put JWT_SECRET
# wrangler secret put JWT_REFRESH_SECRET